package com.trident.security.bean;

import java.util.Date;

public class InVul {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.system_id
     *
     * @mbg.generated
     */
    private Integer systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.serial_num
     *
     * @mbg.generated
     */
    private String serialNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.vul_type
     *
     * @mbg.generated
     */
    private Integer vulType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.risk
     *
     * @mbg.generated
     */
    private Integer risk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.is_need_fix
     *
     * @mbg.generated
     */
    private Integer isNeedFix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.affect
     *
     * @mbg.generated
     */
    private String affect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.fix
     *
     * @mbg.generated
     */
    private String fix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.mitigation
     *
     * @mbg.generated
     */
    private String mitigation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.vul_status
     *
     * @mbg.generated
     */
    private Integer vulStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.fix_status
     *
     * @mbg.generated
     */
    private Integer fixStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.expect_time
     *
     * @mbg.generated
     */
    private Date expectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.fixed_time
     *
     * @mbg.generated
     */
    private Date fixedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.security_user
     *
     * @mbg.generated
     */
    private Long securityUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_vul.security_user_email
     *
     * @mbg.generated
     */
    private String securityUserEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.id
     *
     * @return the value of in_vul.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.id
     *
     * @param id the value for in_vul.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.system_id
     *
     * @return the value of in_vul.system_id
     *
     * @mbg.generated
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.system_id
     *
     * @param systemId the value for in_vul.system_id
     *
     * @mbg.generated
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.title
     *
     * @return the value of in_vul.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.title
     *
     * @param title the value for in_vul.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.serial_num
     *
     * @return the value of in_vul.serial_num
     *
     * @mbg.generated
     */
    public String getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.serial_num
     *
     * @param serialNum the value for in_vul.serial_num
     *
     * @mbg.generated
     */
    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.vul_type
     *
     * @return the value of in_vul.vul_type
     *
     * @mbg.generated
     */
    public Integer getVulType() {
        return vulType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.vul_type
     *
     * @param vulType the value for in_vul.vul_type
     *
     * @mbg.generated
     */
    public void setVulType(Integer vulType) {
        this.vulType = vulType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.risk
     *
     * @return the value of in_vul.risk
     *
     * @mbg.generated
     */
    public Integer getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.risk
     *
     * @param risk the value for in_vul.risk
     *
     * @mbg.generated
     */
    public void setRisk(Integer risk) {
        this.risk = risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.is_need_fix
     *
     * @return the value of in_vul.is_need_fix
     *
     * @mbg.generated
     */
    public Integer getIsNeedFix() {
        return isNeedFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.is_need_fix
     *
     * @param isNeedFix the value for in_vul.is_need_fix
     *
     * @mbg.generated
     */
    public void setIsNeedFix(Integer isNeedFix) {
        this.isNeedFix = isNeedFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.url
     *
     * @return the value of in_vul.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.url
     *
     * @param url the value for in_vul.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.content
     *
     * @return the value of in_vul.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.content
     *
     * @param content the value for in_vul.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.affect
     *
     * @return the value of in_vul.affect
     *
     * @mbg.generated
     */
    public String getAffect() {
        return affect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.affect
     *
     * @param affect the value for in_vul.affect
     *
     * @mbg.generated
     */
    public void setAffect(String affect) {
        this.affect = affect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.fix
     *
     * @return the value of in_vul.fix
     *
     * @mbg.generated
     */
    public String getFix() {
        return fix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.fix
     *
     * @param fix the value for in_vul.fix
     *
     * @mbg.generated
     */
    public void setFix(String fix) {
        this.fix = fix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.mitigation
     *
     * @return the value of in_vul.mitigation
     *
     * @mbg.generated
     */
    public String getMitigation() {
        return mitigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.mitigation
     *
     * @param mitigation the value for in_vul.mitigation
     *
     * @mbg.generated
     */
    public void setMitigation(String mitigation) {
        this.mitigation = mitigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.num
     *
     * @return the value of in_vul.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.num
     *
     * @param num the value for in_vul.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.vul_status
     *
     * @return the value of in_vul.vul_status
     *
     * @mbg.generated
     */
    public Integer getVulStatus() {
        return vulStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.vul_status
     *
     * @param vulStatus the value for in_vul.vul_status
     *
     * @mbg.generated
     */
    public void setVulStatus(Integer vulStatus) {
        this.vulStatus = vulStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.fix_status
     *
     * @return the value of in_vul.fix_status
     *
     * @mbg.generated
     */
    public Integer getFixStatus() {
        return fixStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.fix_status
     *
     * @param fixStatus the value for in_vul.fix_status
     *
     * @mbg.generated
     */
    public void setFixStatus(Integer fixStatus) {
        this.fixStatus = fixStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.create_time
     *
     * @return the value of in_vul.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.create_time
     *
     * @param createTime the value for in_vul.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.expect_time
     *
     * @return the value of in_vul.expect_time
     *
     * @mbg.generated
     */
    public Date getExpectTime() {
        return expectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.expect_time
     *
     * @param expectTime the value for in_vul.expect_time
     *
     * @mbg.generated
     */
    public void setExpectTime(Date expectTime) {
        this.expectTime = expectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.fixed_time
     *
     * @return the value of in_vul.fixed_time
     *
     * @mbg.generated
     */
    public Date getFixedTime() {
        return fixedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.fixed_time
     *
     * @param fixedTime the value for in_vul.fixed_time
     *
     * @mbg.generated
     */
    public void setFixedTime(Date fixedTime) {
        this.fixedTime = fixedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.department
     *
     * @return the value of in_vul.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.department
     *
     * @param department the value for in_vul.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.create_user
     *
     * @return the value of in_vul.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.create_user
     *
     * @param createUser the value for in_vul.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.security_user
     *
     * @return the value of in_vul.security_user
     *
     * @mbg.generated
     */
    public Long getSecurityUser() {
        return securityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.security_user
     *
     * @param securityUser the value for in_vul.security_user
     *
     * @mbg.generated
     */
    public void setSecurityUser(Long securityUser) {
        this.securityUser = securityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_vul.security_user_email
     *
     * @return the value of in_vul.security_user_email
     *
     * @mbg.generated
     */
    public String getSecurityUserEmail() {
        return securityUserEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_vul.security_user_email
     *
     * @param securityUserEmail the value for in_vul.security_user_email
     *
     * @mbg.generated
     */
    public void setSecurityUserEmail(String securityUserEmail) {
        this.securityUserEmail = securityUserEmail;
    }
}