package com.trident.security.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InVulExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public InVulExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNull() {
            addCriterion("system_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNotNull() {
            addCriterion("system_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIdEqualTo(Integer value) {
            addCriterion("system_id =", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotEqualTo(Integer value) {
            addCriterion("system_id <>", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThan(Integer value) {
            addCriterion("system_id >", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_id >=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThan(Integer value) {
            addCriterion("system_id <", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_id <=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdIn(List<Integer> values) {
            addCriterion("system_id in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotIn(List<Integer> values) {
            addCriterion("system_id not in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdBetween(Integer value1, Integer value2) {
            addCriterion("system_id between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_id not between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSerialNumIsNull() {
            addCriterion("serial_num is null");
            return (Criteria) this;
        }

        public Criteria andSerialNumIsNotNull() {
            addCriterion("serial_num is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNumEqualTo(String value) {
            addCriterion("serial_num =", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotEqualTo(String value) {
            addCriterion("serial_num <>", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumGreaterThan(String value) {
            addCriterion("serial_num >", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumGreaterThanOrEqualTo(String value) {
            addCriterion("serial_num >=", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumLessThan(String value) {
            addCriterion("serial_num <", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumLessThanOrEqualTo(String value) {
            addCriterion("serial_num <=", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumLike(String value) {
            addCriterion("serial_num like", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotLike(String value) {
            addCriterion("serial_num not like", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumIn(List<String> values) {
            addCriterion("serial_num in", values, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotIn(List<String> values) {
            addCriterion("serial_num not in", values, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumBetween(String value1, String value2) {
            addCriterion("serial_num between", value1, value2, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotBetween(String value1, String value2) {
            addCriterion("serial_num not between", value1, value2, "serialNum");
            return (Criteria) this;
        }

        public Criteria andVulTypeIsNull() {
            addCriterion("vul_type is null");
            return (Criteria) this;
        }

        public Criteria andVulTypeIsNotNull() {
            addCriterion("vul_type is not null");
            return (Criteria) this;
        }

        public Criteria andVulTypeEqualTo(Integer value) {
            addCriterion("vul_type =", value, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeNotEqualTo(Integer value) {
            addCriterion("vul_type <>", value, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeGreaterThan(Integer value) {
            addCriterion("vul_type >", value, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("vul_type >=", value, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeLessThan(Integer value) {
            addCriterion("vul_type <", value, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeLessThanOrEqualTo(Integer value) {
            addCriterion("vul_type <=", value, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeIn(List<Integer> values) {
            addCriterion("vul_type in", values, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeNotIn(List<Integer> values) {
            addCriterion("vul_type not in", values, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeBetween(Integer value1, Integer value2) {
            addCriterion("vul_type between", value1, value2, "vulType");
            return (Criteria) this;
        }

        public Criteria andVulTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("vul_type not between", value1, value2, "vulType");
            return (Criteria) this;
        }

        public Criteria andRiskIsNull() {
            addCriterion("risk is null");
            return (Criteria) this;
        }

        public Criteria andRiskIsNotNull() {
            addCriterion("risk is not null");
            return (Criteria) this;
        }

        public Criteria andRiskEqualTo(Integer value) {
            addCriterion("risk =", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotEqualTo(Integer value) {
            addCriterion("risk <>", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskGreaterThan(Integer value) {
            addCriterion("risk >", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskGreaterThanOrEqualTo(Integer value) {
            addCriterion("risk >=", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskLessThan(Integer value) {
            addCriterion("risk <", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskLessThanOrEqualTo(Integer value) {
            addCriterion("risk <=", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskIn(List<Integer> values) {
            addCriterion("risk in", values, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotIn(List<Integer> values) {
            addCriterion("risk not in", values, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskBetween(Integer value1, Integer value2) {
            addCriterion("risk between", value1, value2, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotBetween(Integer value1, Integer value2) {
            addCriterion("risk not between", value1, value2, "risk");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixIsNull() {
            addCriterion("is_need_fix is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixIsNotNull() {
            addCriterion("is_need_fix is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixEqualTo(Integer value) {
            addCriterion("is_need_fix =", value, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixNotEqualTo(Integer value) {
            addCriterion("is_need_fix <>", value, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixGreaterThan(Integer value) {
            addCriterion("is_need_fix >", value, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_need_fix >=", value, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixLessThan(Integer value) {
            addCriterion("is_need_fix <", value, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixLessThanOrEqualTo(Integer value) {
            addCriterion("is_need_fix <=", value, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixIn(List<Integer> values) {
            addCriterion("is_need_fix in", values, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixNotIn(List<Integer> values) {
            addCriterion("is_need_fix not in", values, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixBetween(Integer value1, Integer value2) {
            addCriterion("is_need_fix between", value1, value2, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andIsNeedFixNotBetween(Integer value1, Integer value2) {
            addCriterion("is_need_fix not between", value1, value2, "isNeedFix");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andAffectIsNull() {
            addCriterion("affect is null");
            return (Criteria) this;
        }

        public Criteria andAffectIsNotNull() {
            addCriterion("affect is not null");
            return (Criteria) this;
        }

        public Criteria andAffectEqualTo(String value) {
            addCriterion("affect =", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectNotEqualTo(String value) {
            addCriterion("affect <>", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectGreaterThan(String value) {
            addCriterion("affect >", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectGreaterThanOrEqualTo(String value) {
            addCriterion("affect >=", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectLessThan(String value) {
            addCriterion("affect <", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectLessThanOrEqualTo(String value) {
            addCriterion("affect <=", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectLike(String value) {
            addCriterion("affect like", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectNotLike(String value) {
            addCriterion("affect not like", value, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectIn(List<String> values) {
            addCriterion("affect in", values, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectNotIn(List<String> values) {
            addCriterion("affect not in", values, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectBetween(String value1, String value2) {
            addCriterion("affect between", value1, value2, "affect");
            return (Criteria) this;
        }

        public Criteria andAffectNotBetween(String value1, String value2) {
            addCriterion("affect not between", value1, value2, "affect");
            return (Criteria) this;
        }

        public Criteria andFixIsNull() {
            addCriterion("fix is null");
            return (Criteria) this;
        }

        public Criteria andFixIsNotNull() {
            addCriterion("fix is not null");
            return (Criteria) this;
        }

        public Criteria andFixEqualTo(String value) {
            addCriterion("fix =", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixNotEqualTo(String value) {
            addCriterion("fix <>", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixGreaterThan(String value) {
            addCriterion("fix >", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixGreaterThanOrEqualTo(String value) {
            addCriterion("fix >=", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixLessThan(String value) {
            addCriterion("fix <", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixLessThanOrEqualTo(String value) {
            addCriterion("fix <=", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixLike(String value) {
            addCriterion("fix like", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixNotLike(String value) {
            addCriterion("fix not like", value, "fix");
            return (Criteria) this;
        }

        public Criteria andFixIn(List<String> values) {
            addCriterion("fix in", values, "fix");
            return (Criteria) this;
        }

        public Criteria andFixNotIn(List<String> values) {
            addCriterion("fix not in", values, "fix");
            return (Criteria) this;
        }

        public Criteria andFixBetween(String value1, String value2) {
            addCriterion("fix between", value1, value2, "fix");
            return (Criteria) this;
        }

        public Criteria andFixNotBetween(String value1, String value2) {
            addCriterion("fix not between", value1, value2, "fix");
            return (Criteria) this;
        }

        public Criteria andMitigationIsNull() {
            addCriterion("mitigation is null");
            return (Criteria) this;
        }

        public Criteria andMitigationIsNotNull() {
            addCriterion("mitigation is not null");
            return (Criteria) this;
        }

        public Criteria andMitigationEqualTo(String value) {
            addCriterion("mitigation =", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationNotEqualTo(String value) {
            addCriterion("mitigation <>", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationGreaterThan(String value) {
            addCriterion("mitigation >", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationGreaterThanOrEqualTo(String value) {
            addCriterion("mitigation >=", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationLessThan(String value) {
            addCriterion("mitigation <", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationLessThanOrEqualTo(String value) {
            addCriterion("mitigation <=", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationLike(String value) {
            addCriterion("mitigation like", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationNotLike(String value) {
            addCriterion("mitigation not like", value, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationIn(List<String> values) {
            addCriterion("mitigation in", values, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationNotIn(List<String> values) {
            addCriterion("mitigation not in", values, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationBetween(String value1, String value2) {
            addCriterion("mitigation between", value1, value2, "mitigation");
            return (Criteria) this;
        }

        public Criteria andMitigationNotBetween(String value1, String value2) {
            addCriterion("mitigation not between", value1, value2, "mitigation");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andVulStatusIsNull() {
            addCriterion("vul_status is null");
            return (Criteria) this;
        }

        public Criteria andVulStatusIsNotNull() {
            addCriterion("vul_status is not null");
            return (Criteria) this;
        }

        public Criteria andVulStatusEqualTo(Integer value) {
            addCriterion("vul_status =", value, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusNotEqualTo(Integer value) {
            addCriterion("vul_status <>", value, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusGreaterThan(Integer value) {
            addCriterion("vul_status >", value, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("vul_status >=", value, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusLessThan(Integer value) {
            addCriterion("vul_status <", value, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusLessThanOrEqualTo(Integer value) {
            addCriterion("vul_status <=", value, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusIn(List<Integer> values) {
            addCriterion("vul_status in", values, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusNotIn(List<Integer> values) {
            addCriterion("vul_status not in", values, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusBetween(Integer value1, Integer value2) {
            addCriterion("vul_status between", value1, value2, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andVulStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("vul_status not between", value1, value2, "vulStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusIsNull() {
            addCriterion("fix_status is null");
            return (Criteria) this;
        }

        public Criteria andFixStatusIsNotNull() {
            addCriterion("fix_status is not null");
            return (Criteria) this;
        }

        public Criteria andFixStatusEqualTo(Integer value) {
            addCriterion("fix_status =", value, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusNotEqualTo(Integer value) {
            addCriterion("fix_status <>", value, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusGreaterThan(Integer value) {
            addCriterion("fix_status >", value, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("fix_status >=", value, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusLessThan(Integer value) {
            addCriterion("fix_status <", value, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusLessThanOrEqualTo(Integer value) {
            addCriterion("fix_status <=", value, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusIn(List<Integer> values) {
            addCriterion("fix_status in", values, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusNotIn(List<Integer> values) {
            addCriterion("fix_status not in", values, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusBetween(Integer value1, Integer value2) {
            addCriterion("fix_status between", value1, value2, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andFixStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("fix_status not between", value1, value2, "fixStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeIsNull() {
            addCriterion("expect_time is null");
            return (Criteria) this;
        }

        public Criteria andExpectTimeIsNotNull() {
            addCriterion("expect_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpectTimeEqualTo(Date value) {
            addCriterion("expect_time =", value, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeNotEqualTo(Date value) {
            addCriterion("expect_time <>", value, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeGreaterThan(Date value) {
            addCriterion("expect_time >", value, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("expect_time >=", value, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeLessThan(Date value) {
            addCriterion("expect_time <", value, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeLessThanOrEqualTo(Date value) {
            addCriterion("expect_time <=", value, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeIn(List<Date> values) {
            addCriterion("expect_time in", values, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeNotIn(List<Date> values) {
            addCriterion("expect_time not in", values, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeBetween(Date value1, Date value2) {
            addCriterion("expect_time between", value1, value2, "expectTime");
            return (Criteria) this;
        }

        public Criteria andExpectTimeNotBetween(Date value1, Date value2) {
            addCriterion("expect_time not between", value1, value2, "expectTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeIsNull() {
            addCriterion("fixed_time is null");
            return (Criteria) this;
        }

        public Criteria andFixedTimeIsNotNull() {
            addCriterion("fixed_time is not null");
            return (Criteria) this;
        }

        public Criteria andFixedTimeEqualTo(Date value) {
            addCriterion("fixed_time =", value, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeNotEqualTo(Date value) {
            addCriterion("fixed_time <>", value, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeGreaterThan(Date value) {
            addCriterion("fixed_time >", value, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fixed_time >=", value, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeLessThan(Date value) {
            addCriterion("fixed_time <", value, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeLessThanOrEqualTo(Date value) {
            addCriterion("fixed_time <=", value, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeIn(List<Date> values) {
            addCriterion("fixed_time in", values, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeNotIn(List<Date> values) {
            addCriterion("fixed_time not in", values, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeBetween(Date value1, Date value2) {
            addCriterion("fixed_time between", value1, value2, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andFixedTimeNotBetween(Date value1, Date value2) {
            addCriterion("fixed_time not between", value1, value2, "fixedTime");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserIsNull() {
            addCriterion("security_user is null");
            return (Criteria) this;
        }

        public Criteria andSecurityUserIsNotNull() {
            addCriterion("security_user is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEqualTo(Integer value) {
            addCriterion("security_user =", value, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserNotEqualTo(Integer value) {
            addCriterion("security_user <>", value, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserGreaterThan(Integer value) {
            addCriterion("security_user >", value, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("security_user >=", value, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserLessThan(Integer value) {
            addCriterion("security_user <", value, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserLessThanOrEqualTo(Integer value) {
            addCriterion("security_user <=", value, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserIn(List<Integer> values) {
            addCriterion("security_user in", values, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserNotIn(List<Integer> values) {
            addCriterion("security_user not in", values, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserBetween(Integer value1, Integer value2) {
            addCriterion("security_user between", value1, value2, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserNotBetween(Integer value1, Integer value2) {
            addCriterion("security_user not between", value1, value2, "securityUser");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailIsNull() {
            addCriterion("security_user_email is null");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailIsNotNull() {
            addCriterion("security_user_email is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailEqualTo(String value) {
            addCriterion("security_user_email =", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailNotEqualTo(String value) {
            addCriterion("security_user_email <>", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailGreaterThan(String value) {
            addCriterion("security_user_email >", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("security_user_email >=", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailLessThan(String value) {
            addCriterion("security_user_email <", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailLessThanOrEqualTo(String value) {
            addCriterion("security_user_email <=", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailLike(String value) {
            addCriterion("security_user_email like", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailNotLike(String value) {
            addCriterion("security_user_email not like", value, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailIn(List<String> values) {
            addCriterion("security_user_email in", values, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailNotIn(List<String> values) {
            addCriterion("security_user_email not in", values, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailBetween(String value1, String value2) {
            addCriterion("security_user_email between", value1, value2, "securityUserEmail");
            return (Criteria) this;
        }

        public Criteria andSecurityUserEmailNotBetween(String value1, String value2) {
            addCriterion("security_user_email not between", value1, value2, "securityUserEmail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_vul
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}