package com.trident.security.bean;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_module
     *
     * @mbg.generated
     */
    private String logModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.risk
     *
     * @mbg.generated
     */
    private Integer risk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_type
     *
     * @mbg.generated
     */
    private Integer logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_module
     *
     * @return the value of log.log_module
     *
     * @mbg.generated
     */
    public String getLogModule() {
        return logModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_module
     *
     * @param logModule the value for log.log_module
     *
     * @mbg.generated
     */
    public void setLogModule(String logModule) {
        this.logModule = logModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.risk
     *
     * @return the value of log.risk
     *
     * @mbg.generated
     */
    public Integer getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.risk
     *
     * @param risk the value for log.risk
     *
     * @mbg.generated
     */
    public void setRisk(Integer risk) {
        this.risk = risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_type
     *
     * @return the value of log.log_type
     *
     * @mbg.generated
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_type
     *
     * @param logType the value for log.log_type
     *
     * @mbg.generated
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.result
     *
     * @return the value of log.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.result
     *
     * @param result the value for log.result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.msg
     *
     * @return the value of log.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.msg
     *
     * @param msg the value for log.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_id
     *
     * @return the value of log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_id
     *
     * @param userId the value for log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.create_time
     *
     * @return the value of log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.create_time
     *
     * @param createTime the value for log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}