package com.trident.security.bean;

import java.util.Date;

public class OutVul {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.vul_type
     *
     * @mbg.generated
     */
    private Integer vulType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.cve
     *
     * @mbg.generated
     */
    private String cve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.risk
     *
     * @mbg.generated
     */
    private Integer risk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.affect
     *
     * @mbg.generated
     */
    private String affect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.fix
     *
     * @mbg.generated
     */
    private String fix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.hot
     *
     * @mbg.generated
     */
    private Integer hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.show_time
     *
     * @mbg.generated
     */
    private Date showTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_vul.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.id
     *
     * @return the value of out_vul.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.id
     *
     * @param id the value for out_vul.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.title
     *
     * @return the value of out_vul.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.title
     *
     * @param title the value for out_vul.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.vul_type
     *
     * @return the value of out_vul.vul_type
     *
     * @mbg.generated
     */
    public Integer getVulType() {
        return vulType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.vul_type
     *
     * @param vulType the value for out_vul.vul_type
     *
     * @mbg.generated
     */
    public void setVulType(Integer vulType) {
        this.vulType = vulType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.cve
     *
     * @return the value of out_vul.cve
     *
     * @mbg.generated
     */
    public String getCve() {
        return cve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.cve
     *
     * @param cve the value for out_vul.cve
     *
     * @mbg.generated
     */
    public void setCve(String cve) {
        this.cve = cve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.risk
     *
     * @return the value of out_vul.risk
     *
     * @mbg.generated
     */
    public Integer getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.risk
     *
     * @param risk the value for out_vul.risk
     *
     * @mbg.generated
     */
    public void setRisk(Integer risk) {
        this.risk = risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.affect
     *
     * @return the value of out_vul.affect
     *
     * @mbg.generated
     */
    public String getAffect() {
        return affect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.affect
     *
     * @param affect the value for out_vul.affect
     *
     * @mbg.generated
     */
    public void setAffect(String affect) {
        this.affect = affect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.content
     *
     * @return the value of out_vul.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.content
     *
     * @param content the value for out_vul.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.fix
     *
     * @return the value of out_vul.fix
     *
     * @mbg.generated
     */
    public String getFix() {
        return fix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.fix
     *
     * @param fix the value for out_vul.fix
     *
     * @mbg.generated
     */
    public void setFix(String fix) {
        this.fix = fix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.status
     *
     * @return the value of out_vul.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.status
     *
     * @param status the value for out_vul.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.num
     *
     * @return the value of out_vul.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.num
     *
     * @param num the value for out_vul.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.hot
     *
     * @return the value of out_vul.hot
     *
     * @mbg.generated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.hot
     *
     * @param hot the value for out_vul.hot
     *
     * @mbg.generated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.show_time
     *
     * @return the value of out_vul.show_time
     *
     * @mbg.generated
     */
    public Date getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.show_time
     *
     * @param showTime the value for out_vul.show_time
     *
     * @mbg.generated
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.create_time
     *
     * @return the value of out_vul.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.create_time
     *
     * @param createTime the value for out_vul.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_vul.update_time
     *
     * @return the value of out_vul.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_vul.update_time
     *
     * @param updateTime the value for out_vul.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}