package com.trident.security.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public SystemInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNull() {
            addCriterion("full_name is null");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNotNull() {
            addCriterion("full_name is not null");
            return (Criteria) this;
        }

        public Criteria andFullNameEqualTo(String value) {
            addCriterion("full_name =", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotEqualTo(String value) {
            addCriterion("full_name <>", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThan(String value) {
            addCriterion("full_name >", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("full_name >=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThan(String value) {
            addCriterion("full_name <", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThanOrEqualTo(String value) {
            addCriterion("full_name <=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLike(String value) {
            addCriterion("full_name like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotLike(String value) {
            addCriterion("full_name not like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameIn(List<String> values) {
            addCriterion("full_name in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotIn(List<String> values) {
            addCriterion("full_name not in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameBetween(String value1, String value2) {
            addCriterion("full_name between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotBetween(String value1, String value2) {
            addCriterion("full_name not between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("owner like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("owner not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andSitAddressIsNull() {
            addCriterion("sit_address is null");
            return (Criteria) this;
        }

        public Criteria andSitAddressIsNotNull() {
            addCriterion("sit_address is not null");
            return (Criteria) this;
        }

        public Criteria andSitAddressEqualTo(String value) {
            addCriterion("sit_address =", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressNotEqualTo(String value) {
            addCriterion("sit_address <>", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressGreaterThan(String value) {
            addCriterion("sit_address >", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sit_address >=", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressLessThan(String value) {
            addCriterion("sit_address <", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressLessThanOrEqualTo(String value) {
            addCriterion("sit_address <=", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressLike(String value) {
            addCriterion("sit_address like", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressNotLike(String value) {
            addCriterion("sit_address not like", value, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressIn(List<String> values) {
            addCriterion("sit_address in", values, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressNotIn(List<String> values) {
            addCriterion("sit_address not in", values, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressBetween(String value1, String value2) {
            addCriterion("sit_address between", value1, value2, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitAddressNotBetween(String value1, String value2) {
            addCriterion("sit_address not between", value1, value2, "sitAddress");
            return (Criteria) this;
        }

        public Criteria andSitUsernameIsNull() {
            addCriterion("sit_username is null");
            return (Criteria) this;
        }

        public Criteria andSitUsernameIsNotNull() {
            addCriterion("sit_username is not null");
            return (Criteria) this;
        }

        public Criteria andSitUsernameEqualTo(String value) {
            addCriterion("sit_username =", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameNotEqualTo(String value) {
            addCriterion("sit_username <>", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameGreaterThan(String value) {
            addCriterion("sit_username >", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("sit_username >=", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameLessThan(String value) {
            addCriterion("sit_username <", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameLessThanOrEqualTo(String value) {
            addCriterion("sit_username <=", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameLike(String value) {
            addCriterion("sit_username like", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameNotLike(String value) {
            addCriterion("sit_username not like", value, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameIn(List<String> values) {
            addCriterion("sit_username in", values, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameNotIn(List<String> values) {
            addCriterion("sit_username not in", values, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameBetween(String value1, String value2) {
            addCriterion("sit_username between", value1, value2, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitUsernameNotBetween(String value1, String value2) {
            addCriterion("sit_username not between", value1, value2, "sitUsername");
            return (Criteria) this;
        }

        public Criteria andSitPasswordIsNull() {
            addCriterion("sit_password is null");
            return (Criteria) this;
        }

        public Criteria andSitPasswordIsNotNull() {
            addCriterion("sit_password is not null");
            return (Criteria) this;
        }

        public Criteria andSitPasswordEqualTo(String value) {
            addCriterion("sit_password =", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordNotEqualTo(String value) {
            addCriterion("sit_password <>", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordGreaterThan(String value) {
            addCriterion("sit_password >", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("sit_password >=", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordLessThan(String value) {
            addCriterion("sit_password <", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordLessThanOrEqualTo(String value) {
            addCriterion("sit_password <=", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordLike(String value) {
            addCriterion("sit_password like", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordNotLike(String value) {
            addCriterion("sit_password not like", value, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordIn(List<String> values) {
            addCriterion("sit_password in", values, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordNotIn(List<String> values) {
            addCriterion("sit_password not in", values, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordBetween(String value1, String value2) {
            addCriterion("sit_password between", value1, value2, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andSitPasswordNotBetween(String value1, String value2) {
            addCriterion("sit_password not between", value1, value2, "sitPassword");
            return (Criteria) this;
        }

        public Criteria andUatAddressIsNull() {
            addCriterion("uat_address is null");
            return (Criteria) this;
        }

        public Criteria andUatAddressIsNotNull() {
            addCriterion("uat_address is not null");
            return (Criteria) this;
        }

        public Criteria andUatAddressEqualTo(String value) {
            addCriterion("uat_address =", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressNotEqualTo(String value) {
            addCriterion("uat_address <>", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressGreaterThan(String value) {
            addCriterion("uat_address >", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressGreaterThanOrEqualTo(String value) {
            addCriterion("uat_address >=", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressLessThan(String value) {
            addCriterion("uat_address <", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressLessThanOrEqualTo(String value) {
            addCriterion("uat_address <=", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressLike(String value) {
            addCriterion("uat_address like", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressNotLike(String value) {
            addCriterion("uat_address not like", value, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressIn(List<String> values) {
            addCriterion("uat_address in", values, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressNotIn(List<String> values) {
            addCriterion("uat_address not in", values, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressBetween(String value1, String value2) {
            addCriterion("uat_address between", value1, value2, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatAddressNotBetween(String value1, String value2) {
            addCriterion("uat_address not between", value1, value2, "uatAddress");
            return (Criteria) this;
        }

        public Criteria andUatUsernameIsNull() {
            addCriterion("uat_username is null");
            return (Criteria) this;
        }

        public Criteria andUatUsernameIsNotNull() {
            addCriterion("uat_username is not null");
            return (Criteria) this;
        }

        public Criteria andUatUsernameEqualTo(String value) {
            addCriterion("uat_username =", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameNotEqualTo(String value) {
            addCriterion("uat_username <>", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameGreaterThan(String value) {
            addCriterion("uat_username >", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("uat_username >=", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameLessThan(String value) {
            addCriterion("uat_username <", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameLessThanOrEqualTo(String value) {
            addCriterion("uat_username <=", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameLike(String value) {
            addCriterion("uat_username like", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameNotLike(String value) {
            addCriterion("uat_username not like", value, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameIn(List<String> values) {
            addCriterion("uat_username in", values, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameNotIn(List<String> values) {
            addCriterion("uat_username not in", values, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameBetween(String value1, String value2) {
            addCriterion("uat_username between", value1, value2, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatUsernameNotBetween(String value1, String value2) {
            addCriterion("uat_username not between", value1, value2, "uatUsername");
            return (Criteria) this;
        }

        public Criteria andUatPasswordIsNull() {
            addCriterion("uat_password is null");
            return (Criteria) this;
        }

        public Criteria andUatPasswordIsNotNull() {
            addCriterion("uat_password is not null");
            return (Criteria) this;
        }

        public Criteria andUatPasswordEqualTo(String value) {
            addCriterion("uat_password =", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordNotEqualTo(String value) {
            addCriterion("uat_password <>", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordGreaterThan(String value) {
            addCriterion("uat_password >", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("uat_password >=", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordLessThan(String value) {
            addCriterion("uat_password <", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordLessThanOrEqualTo(String value) {
            addCriterion("uat_password <=", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordLike(String value) {
            addCriterion("uat_password like", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordNotLike(String value) {
            addCriterion("uat_password not like", value, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordIn(List<String> values) {
            addCriterion("uat_password in", values, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordNotIn(List<String> values) {
            addCriterion("uat_password not in", values, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordBetween(String value1, String value2) {
            addCriterion("uat_password between", value1, value2, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andUatPasswordNotBetween(String value1, String value2) {
            addCriterion("uat_password not between", value1, value2, "uatPassword");
            return (Criteria) this;
        }

        public Criteria andDevAddressIsNull() {
            addCriterion("dev_address is null");
            return (Criteria) this;
        }

        public Criteria andDevAddressIsNotNull() {
            addCriterion("dev_address is not null");
            return (Criteria) this;
        }

        public Criteria andDevAddressEqualTo(String value) {
            addCriterion("dev_address =", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressNotEqualTo(String value) {
            addCriterion("dev_address <>", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressGreaterThan(String value) {
            addCriterion("dev_address >", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressGreaterThanOrEqualTo(String value) {
            addCriterion("dev_address >=", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressLessThan(String value) {
            addCriterion("dev_address <", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressLessThanOrEqualTo(String value) {
            addCriterion("dev_address <=", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressLike(String value) {
            addCriterion("dev_address like", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressNotLike(String value) {
            addCriterion("dev_address not like", value, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressIn(List<String> values) {
            addCriterion("dev_address in", values, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressNotIn(List<String> values) {
            addCriterion("dev_address not in", values, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressBetween(String value1, String value2) {
            addCriterion("dev_address between", value1, value2, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevAddressNotBetween(String value1, String value2) {
            addCriterion("dev_address not between", value1, value2, "devAddress");
            return (Criteria) this;
        }

        public Criteria andDevUsernameIsNull() {
            addCriterion("dev_username is null");
            return (Criteria) this;
        }

        public Criteria andDevUsernameIsNotNull() {
            addCriterion("dev_username is not null");
            return (Criteria) this;
        }

        public Criteria andDevUsernameEqualTo(String value) {
            addCriterion("dev_username =", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameNotEqualTo(String value) {
            addCriterion("dev_username <>", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameGreaterThan(String value) {
            addCriterion("dev_username >", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("dev_username >=", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameLessThan(String value) {
            addCriterion("dev_username <", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameLessThanOrEqualTo(String value) {
            addCriterion("dev_username <=", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameLike(String value) {
            addCriterion("dev_username like", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameNotLike(String value) {
            addCriterion("dev_username not like", value, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameIn(List<String> values) {
            addCriterion("dev_username in", values, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameNotIn(List<String> values) {
            addCriterion("dev_username not in", values, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameBetween(String value1, String value2) {
            addCriterion("dev_username between", value1, value2, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevUsernameNotBetween(String value1, String value2) {
            addCriterion("dev_username not between", value1, value2, "devUsername");
            return (Criteria) this;
        }

        public Criteria andDevPasswordIsNull() {
            addCriterion("dev_password is null");
            return (Criteria) this;
        }

        public Criteria andDevPasswordIsNotNull() {
            addCriterion("dev_password is not null");
            return (Criteria) this;
        }

        public Criteria andDevPasswordEqualTo(String value) {
            addCriterion("dev_password =", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordNotEqualTo(String value) {
            addCriterion("dev_password <>", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordGreaterThan(String value) {
            addCriterion("dev_password >", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("dev_password >=", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordLessThan(String value) {
            addCriterion("dev_password <", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordLessThanOrEqualTo(String value) {
            addCriterion("dev_password <=", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordLike(String value) {
            addCriterion("dev_password like", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordNotLike(String value) {
            addCriterion("dev_password not like", value, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordIn(List<String> values) {
            addCriterion("dev_password in", values, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordNotIn(List<String> values) {
            addCriterion("dev_password not in", values, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordBetween(String value1, String value2) {
            addCriterion("dev_password between", value1, value2, "devPassword");
            return (Criteria) this;
        }

        public Criteria andDevPasswordNotBetween(String value1, String value2) {
            addCriterion("dev_password not between", value1, value2, "devPassword");
            return (Criteria) this;
        }

        public Criteria andProdAddressIsNull() {
            addCriterion("prod_address is null");
            return (Criteria) this;
        }

        public Criteria andProdAddressIsNotNull() {
            addCriterion("prod_address is not null");
            return (Criteria) this;
        }

        public Criteria andProdAddressEqualTo(String value) {
            addCriterion("prod_address =", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressNotEqualTo(String value) {
            addCriterion("prod_address <>", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressGreaterThan(String value) {
            addCriterion("prod_address >", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressGreaterThanOrEqualTo(String value) {
            addCriterion("prod_address >=", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressLessThan(String value) {
            addCriterion("prod_address <", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressLessThanOrEqualTo(String value) {
            addCriterion("prod_address <=", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressLike(String value) {
            addCriterion("prod_address like", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressNotLike(String value) {
            addCriterion("prod_address not like", value, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressIn(List<String> values) {
            addCriterion("prod_address in", values, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressNotIn(List<String> values) {
            addCriterion("prod_address not in", values, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressBetween(String value1, String value2) {
            addCriterion("prod_address between", value1, value2, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdAddressNotBetween(String value1, String value2) {
            addCriterion("prod_address not between", value1, value2, "prodAddress");
            return (Criteria) this;
        }

        public Criteria andProdUsernameIsNull() {
            addCriterion("prod_username is null");
            return (Criteria) this;
        }

        public Criteria andProdUsernameIsNotNull() {
            addCriterion("prod_username is not null");
            return (Criteria) this;
        }

        public Criteria andProdUsernameEqualTo(String value) {
            addCriterion("prod_username =", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameNotEqualTo(String value) {
            addCriterion("prod_username <>", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameGreaterThan(String value) {
            addCriterion("prod_username >", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("prod_username >=", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameLessThan(String value) {
            addCriterion("prod_username <", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameLessThanOrEqualTo(String value) {
            addCriterion("prod_username <=", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameLike(String value) {
            addCriterion("prod_username like", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameNotLike(String value) {
            addCriterion("prod_username not like", value, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameIn(List<String> values) {
            addCriterion("prod_username in", values, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameNotIn(List<String> values) {
            addCriterion("prod_username not in", values, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameBetween(String value1, String value2) {
            addCriterion("prod_username between", value1, value2, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdUsernameNotBetween(String value1, String value2) {
            addCriterion("prod_username not between", value1, value2, "prodUsername");
            return (Criteria) this;
        }

        public Criteria andProdPasswordIsNull() {
            addCriterion("prod_password is null");
            return (Criteria) this;
        }

        public Criteria andProdPasswordIsNotNull() {
            addCriterion("prod_password is not null");
            return (Criteria) this;
        }

        public Criteria andProdPasswordEqualTo(String value) {
            addCriterion("prod_password =", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordNotEqualTo(String value) {
            addCriterion("prod_password <>", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordGreaterThan(String value) {
            addCriterion("prod_password >", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("prod_password >=", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordLessThan(String value) {
            addCriterion("prod_password <", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordLessThanOrEqualTo(String value) {
            addCriterion("prod_password <=", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordLike(String value) {
            addCriterion("prod_password like", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordNotLike(String value) {
            addCriterion("prod_password not like", value, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordIn(List<String> values) {
            addCriterion("prod_password in", values, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordNotIn(List<String> values) {
            addCriterion("prod_password not in", values, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordBetween(String value1, String value2) {
            addCriterion("prod_password between", value1, value2, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andProdPasswordNotBetween(String value1, String value2) {
            addCriterion("prod_password not between", value1, value2, "prodPassword");
            return (Criteria) this;
        }

        public Criteria andPmNameIsNull() {
            addCriterion("pm_name is null");
            return (Criteria) this;
        }

        public Criteria andPmNameIsNotNull() {
            addCriterion("pm_name is not null");
            return (Criteria) this;
        }

        public Criteria andPmNameEqualTo(String value) {
            addCriterion("pm_name =", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotEqualTo(String value) {
            addCriterion("pm_name <>", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameGreaterThan(String value) {
            addCriterion("pm_name >", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameGreaterThanOrEqualTo(String value) {
            addCriterion("pm_name >=", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameLessThan(String value) {
            addCriterion("pm_name <", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameLessThanOrEqualTo(String value) {
            addCriterion("pm_name <=", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameLike(String value) {
            addCriterion("pm_name like", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotLike(String value) {
            addCriterion("pm_name not like", value, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameIn(List<String> values) {
            addCriterion("pm_name in", values, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotIn(List<String> values) {
            addCriterion("pm_name not in", values, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameBetween(String value1, String value2) {
            addCriterion("pm_name between", value1, value2, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmNameNotBetween(String value1, String value2) {
            addCriterion("pm_name not between", value1, value2, "pmName");
            return (Criteria) this;
        }

        public Criteria andPmEmailIsNull() {
            addCriterion("pm_email is null");
            return (Criteria) this;
        }

        public Criteria andPmEmailIsNotNull() {
            addCriterion("pm_email is not null");
            return (Criteria) this;
        }

        public Criteria andPmEmailEqualTo(String value) {
            addCriterion("pm_email =", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailNotEqualTo(String value) {
            addCriterion("pm_email <>", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailGreaterThan(String value) {
            addCriterion("pm_email >", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailGreaterThanOrEqualTo(String value) {
            addCriterion("pm_email >=", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailLessThan(String value) {
            addCriterion("pm_email <", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailLessThanOrEqualTo(String value) {
            addCriterion("pm_email <=", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailLike(String value) {
            addCriterion("pm_email like", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailNotLike(String value) {
            addCriterion("pm_email not like", value, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailIn(List<String> values) {
            addCriterion("pm_email in", values, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailNotIn(List<String> values) {
            addCriterion("pm_email not in", values, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailBetween(String value1, String value2) {
            addCriterion("pm_email between", value1, value2, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmEmailNotBetween(String value1, String value2) {
            addCriterion("pm_email not between", value1, value2, "pmEmail");
            return (Criteria) this;
        }

        public Criteria andPmPhoneIsNull() {
            addCriterion("pm_phone is null");
            return (Criteria) this;
        }

        public Criteria andPmPhoneIsNotNull() {
            addCriterion("pm_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPmPhoneEqualTo(String value) {
            addCriterion("pm_phone =", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotEqualTo(String value) {
            addCriterion("pm_phone <>", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneGreaterThan(String value) {
            addCriterion("pm_phone >", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("pm_phone >=", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneLessThan(String value) {
            addCriterion("pm_phone <", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneLessThanOrEqualTo(String value) {
            addCriterion("pm_phone <=", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneLike(String value) {
            addCriterion("pm_phone like", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotLike(String value) {
            addCriterion("pm_phone not like", value, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneIn(List<String> values) {
            addCriterion("pm_phone in", values, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotIn(List<String> values) {
            addCriterion("pm_phone not in", values, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneBetween(String value1, String value2) {
            addCriterion("pm_phone between", value1, value2, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmPhoneNotBetween(String value1, String value2) {
            addCriterion("pm_phone not between", value1, value2, "pmPhone");
            return (Criteria) this;
        }

        public Criteria andPmManagerIsNull() {
            addCriterion("pm_manager is null");
            return (Criteria) this;
        }

        public Criteria andPmManagerIsNotNull() {
            addCriterion("pm_manager is not null");
            return (Criteria) this;
        }

        public Criteria andPmManagerEqualTo(String value) {
            addCriterion("pm_manager =", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerNotEqualTo(String value) {
            addCriterion("pm_manager <>", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerGreaterThan(String value) {
            addCriterion("pm_manager >", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerGreaterThanOrEqualTo(String value) {
            addCriterion("pm_manager >=", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerLessThan(String value) {
            addCriterion("pm_manager <", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerLessThanOrEqualTo(String value) {
            addCriterion("pm_manager <=", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerLike(String value) {
            addCriterion("pm_manager like", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerNotLike(String value) {
            addCriterion("pm_manager not like", value, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerIn(List<String> values) {
            addCriterion("pm_manager in", values, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerNotIn(List<String> values) {
            addCriterion("pm_manager not in", values, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerBetween(String value1, String value2) {
            addCriterion("pm_manager between", value1, value2, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerNotBetween(String value1, String value2) {
            addCriterion("pm_manager not between", value1, value2, "pmManager");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailIsNull() {
            addCriterion("pm_manager_email is null");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailIsNotNull() {
            addCriterion("pm_manager_email is not null");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailEqualTo(String value) {
            addCriterion("pm_manager_email =", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailNotEqualTo(String value) {
            addCriterion("pm_manager_email <>", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailGreaterThan(String value) {
            addCriterion("pm_manager_email >", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailGreaterThanOrEqualTo(String value) {
            addCriterion("pm_manager_email >=", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailLessThan(String value) {
            addCriterion("pm_manager_email <", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailLessThanOrEqualTo(String value) {
            addCriterion("pm_manager_email <=", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailLike(String value) {
            addCriterion("pm_manager_email like", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailNotLike(String value) {
            addCriterion("pm_manager_email not like", value, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailIn(List<String> values) {
            addCriterion("pm_manager_email in", values, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailNotIn(List<String> values) {
            addCriterion("pm_manager_email not in", values, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailBetween(String value1, String value2) {
            addCriterion("pm_manager_email between", value1, value2, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmManagerEmailNotBetween(String value1, String value2) {
            addCriterion("pm_manager_email not between", value1, value2, "pmManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerIsNull() {
            addCriterion("dev_manager is null");
            return (Criteria) this;
        }

        public Criteria andDevManagerIsNotNull() {
            addCriterion("dev_manager is not null");
            return (Criteria) this;
        }

        public Criteria andDevManagerEqualTo(String value) {
            addCriterion("dev_manager =", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerNotEqualTo(String value) {
            addCriterion("dev_manager <>", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerGreaterThan(String value) {
            addCriterion("dev_manager >", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerGreaterThanOrEqualTo(String value) {
            addCriterion("dev_manager >=", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerLessThan(String value) {
            addCriterion("dev_manager <", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerLessThanOrEqualTo(String value) {
            addCriterion("dev_manager <=", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerLike(String value) {
            addCriterion("dev_manager like", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerNotLike(String value) {
            addCriterion("dev_manager not like", value, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerIn(List<String> values) {
            addCriterion("dev_manager in", values, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerNotIn(List<String> values) {
            addCriterion("dev_manager not in", values, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerBetween(String value1, String value2) {
            addCriterion("dev_manager between", value1, value2, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerNotBetween(String value1, String value2) {
            addCriterion("dev_manager not between", value1, value2, "devManager");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailIsNull() {
            addCriterion("dev_manager_email is null");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailIsNotNull() {
            addCriterion("dev_manager_email is not null");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailEqualTo(String value) {
            addCriterion("dev_manager_email =", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailNotEqualTo(String value) {
            addCriterion("dev_manager_email <>", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailGreaterThan(String value) {
            addCriterion("dev_manager_email >", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailGreaterThanOrEqualTo(String value) {
            addCriterion("dev_manager_email >=", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailLessThan(String value) {
            addCriterion("dev_manager_email <", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailLessThanOrEqualTo(String value) {
            addCriterion("dev_manager_email <=", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailLike(String value) {
            addCriterion("dev_manager_email like", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailNotLike(String value) {
            addCriterion("dev_manager_email not like", value, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailIn(List<String> values) {
            addCriterion("dev_manager_email in", values, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailNotIn(List<String> values) {
            addCriterion("dev_manager_email not in", values, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailBetween(String value1, String value2) {
            addCriterion("dev_manager_email between", value1, value2, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andDevManagerEmailNotBetween(String value1, String value2) {
            addCriterion("dev_manager_email not between", value1, value2, "devManagerEmail");
            return (Criteria) this;
        }

        public Criteria andPmoIsNull() {
            addCriterion("pmo is null");
            return (Criteria) this;
        }

        public Criteria andPmoIsNotNull() {
            addCriterion("pmo is not null");
            return (Criteria) this;
        }

        public Criteria andPmoEqualTo(String value) {
            addCriterion("pmo =", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoNotEqualTo(String value) {
            addCriterion("pmo <>", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoGreaterThan(String value) {
            addCriterion("pmo >", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoGreaterThanOrEqualTo(String value) {
            addCriterion("pmo >=", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoLessThan(String value) {
            addCriterion("pmo <", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoLessThanOrEqualTo(String value) {
            addCriterion("pmo <=", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoLike(String value) {
            addCriterion("pmo like", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoNotLike(String value) {
            addCriterion("pmo not like", value, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoIn(List<String> values) {
            addCriterion("pmo in", values, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoNotIn(List<String> values) {
            addCriterion("pmo not in", values, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoBetween(String value1, String value2) {
            addCriterion("pmo between", value1, value2, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoNotBetween(String value1, String value2) {
            addCriterion("pmo not between", value1, value2, "pmo");
            return (Criteria) this;
        }

        public Criteria andPmoEmailIsNull() {
            addCriterion("pmo_email is null");
            return (Criteria) this;
        }

        public Criteria andPmoEmailIsNotNull() {
            addCriterion("pmo_email is not null");
            return (Criteria) this;
        }

        public Criteria andPmoEmailEqualTo(String value) {
            addCriterion("pmo_email =", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailNotEqualTo(String value) {
            addCriterion("pmo_email <>", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailGreaterThan(String value) {
            addCriterion("pmo_email >", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailGreaterThanOrEqualTo(String value) {
            addCriterion("pmo_email >=", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailLessThan(String value) {
            addCriterion("pmo_email <", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailLessThanOrEqualTo(String value) {
            addCriterion("pmo_email <=", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailLike(String value) {
            addCriterion("pmo_email like", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailNotLike(String value) {
            addCriterion("pmo_email not like", value, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailIn(List<String> values) {
            addCriterion("pmo_email in", values, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailNotIn(List<String> values) {
            addCriterion("pmo_email not in", values, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailBetween(String value1, String value2) {
            addCriterion("pmo_email between", value1, value2, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andPmoEmailNotBetween(String value1, String value2) {
            addCriterion("pmo_email not between", value1, value2, "pmoEmail");
            return (Criteria) this;
        }

        public Criteria andVendorNameIsNull() {
            addCriterion("vendor_name is null");
            return (Criteria) this;
        }

        public Criteria andVendorNameIsNotNull() {
            addCriterion("vendor_name is not null");
            return (Criteria) this;
        }

        public Criteria andVendorNameEqualTo(String value) {
            addCriterion("vendor_name =", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameNotEqualTo(String value) {
            addCriterion("vendor_name <>", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameGreaterThan(String value) {
            addCriterion("vendor_name >", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameGreaterThanOrEqualTo(String value) {
            addCriterion("vendor_name >=", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameLessThan(String value) {
            addCriterion("vendor_name <", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameLessThanOrEqualTo(String value) {
            addCriterion("vendor_name <=", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameLike(String value) {
            addCriterion("vendor_name like", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameNotLike(String value) {
            addCriterion("vendor_name not like", value, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameIn(List<String> values) {
            addCriterion("vendor_name in", values, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameNotIn(List<String> values) {
            addCriterion("vendor_name not in", values, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameBetween(String value1, String value2) {
            addCriterion("vendor_name between", value1, value2, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorNameNotBetween(String value1, String value2) {
            addCriterion("vendor_name not between", value1, value2, "vendorName");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1IsNull() {
            addCriterion("vendor_email1 is null");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1IsNotNull() {
            addCriterion("vendor_email1 is not null");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1EqualTo(String value) {
            addCriterion("vendor_email1 =", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1NotEqualTo(String value) {
            addCriterion("vendor_email1 <>", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1GreaterThan(String value) {
            addCriterion("vendor_email1 >", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1GreaterThanOrEqualTo(String value) {
            addCriterion("vendor_email1 >=", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1LessThan(String value) {
            addCriterion("vendor_email1 <", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1LessThanOrEqualTo(String value) {
            addCriterion("vendor_email1 <=", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1Like(String value) {
            addCriterion("vendor_email1 like", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1NotLike(String value) {
            addCriterion("vendor_email1 not like", value, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1In(List<String> values) {
            addCriterion("vendor_email1 in", values, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1NotIn(List<String> values) {
            addCriterion("vendor_email1 not in", values, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1Between(String value1, String value2) {
            addCriterion("vendor_email1 between", value1, value2, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail1NotBetween(String value1, String value2) {
            addCriterion("vendor_email1 not between", value1, value2, "vendorEmail1");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2IsNull() {
            addCriterion("vendor_email2 is null");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2IsNotNull() {
            addCriterion("vendor_email2 is not null");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2EqualTo(String value) {
            addCriterion("vendor_email2 =", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2NotEqualTo(String value) {
            addCriterion("vendor_email2 <>", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2GreaterThan(String value) {
            addCriterion("vendor_email2 >", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2GreaterThanOrEqualTo(String value) {
            addCriterion("vendor_email2 >=", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2LessThan(String value) {
            addCriterion("vendor_email2 <", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2LessThanOrEqualTo(String value) {
            addCriterion("vendor_email2 <=", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2Like(String value) {
            addCriterion("vendor_email2 like", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2NotLike(String value) {
            addCriterion("vendor_email2 not like", value, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2In(List<String> values) {
            addCriterion("vendor_email2 in", values, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2NotIn(List<String> values) {
            addCriterion("vendor_email2 not in", values, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2Between(String value1, String value2) {
            addCriterion("vendor_email2 between", value1, value2, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail2NotBetween(String value1, String value2) {
            addCriterion("vendor_email2 not between", value1, value2, "vendorEmail2");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3IsNull() {
            addCriterion("vendor_email3 is null");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3IsNotNull() {
            addCriterion("vendor_email3 is not null");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3EqualTo(String value) {
            addCriterion("vendor_email3 =", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3NotEqualTo(String value) {
            addCriterion("vendor_email3 <>", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3GreaterThan(String value) {
            addCriterion("vendor_email3 >", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3GreaterThanOrEqualTo(String value) {
            addCriterion("vendor_email3 >=", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3LessThan(String value) {
            addCriterion("vendor_email3 <", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3LessThanOrEqualTo(String value) {
            addCriterion("vendor_email3 <=", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3Like(String value) {
            addCriterion("vendor_email3 like", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3NotLike(String value) {
            addCriterion("vendor_email3 not like", value, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3In(List<String> values) {
            addCriterion("vendor_email3 in", values, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3NotIn(List<String> values) {
            addCriterion("vendor_email3 not in", values, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3Between(String value1, String value2) {
            addCriterion("vendor_email3 between", value1, value2, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andVendorEmail3NotBetween(String value1, String value2) {
            addCriterion("vendor_email3 not between", value1, value2, "vendorEmail3");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}