package com.trident.security.bean;

import java.util.Date;

public class SystemInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.owner
     *
     * @mbg.generated
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.sit_address
     *
     * @mbg.generated
     */
    private String sitAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.sit_username
     *
     * @mbg.generated
     */
    private String sitUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.sit_password
     *
     * @mbg.generated
     */
    private String sitPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.uat_address
     *
     * @mbg.generated
     */
    private String uatAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.uat_username
     *
     * @mbg.generated
     */
    private String uatUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.uat_password
     *
     * @mbg.generated
     */
    private String uatPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.dev_address
     *
     * @mbg.generated
     */
    private String devAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.dev_username
     *
     * @mbg.generated
     */
    private String devUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.dev_password
     *
     * @mbg.generated
     */
    private String devPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.prod_address
     *
     * @mbg.generated
     */
    private String prodAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.prod_username
     *
     * @mbg.generated
     */
    private String prodUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.prod_password
     *
     * @mbg.generated
     */
    private String prodPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pm_name
     *
     * @mbg.generated
     */
    private String pmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pm_email
     *
     * @mbg.generated
     */
    private String pmEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pm_phone
     *
     * @mbg.generated
     */
    private String pmPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pm_manager
     *
     * @mbg.generated
     */
    private String pmManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pm_manager_email
     *
     * @mbg.generated
     */
    private String pmManagerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.dev_manager
     *
     * @mbg.generated
     */
    private String devManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.dev_manager_email
     *
     * @mbg.generated
     */
    private String devManagerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pmo
     *
     * @mbg.generated
     */
    private String pmo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.pmo_email
     *
     * @mbg.generated
     */
    private String pmoEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.vendor_name
     *
     * @mbg.generated
     */
    private String vendorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.vendor_email1
     *
     * @mbg.generated
     */
    private String vendorEmail1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.vendor_email2
     *
     * @mbg.generated
     */
    private String vendorEmail2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.vendor_email3
     *
     * @mbg.generated
     */
    private String vendorEmail3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.id
     *
     * @return the value of system_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.id
     *
     * @param id the value for system_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.name
     *
     * @return the value of system_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.name
     *
     * @param name the value for system_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.full_name
     *
     * @return the value of system_info.full_name
     *
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.full_name
     *
     * @param fullName the value for system_info.full_name
     *
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.department
     *
     * @return the value of system_info.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.department
     *
     * @param department the value for system_info.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.owner
     *
     * @return the value of system_info.owner
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.owner
     *
     * @param owner the value for system_info.owner
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.sit_address
     *
     * @return the value of system_info.sit_address
     *
     * @mbg.generated
     */
    public String getSitAddress() {
        return sitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.sit_address
     *
     * @param sitAddress the value for system_info.sit_address
     *
     * @mbg.generated
     */
    public void setSitAddress(String sitAddress) {
        this.sitAddress = sitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.sit_username
     *
     * @return the value of system_info.sit_username
     *
     * @mbg.generated
     */
    public String getSitUsername() {
        return sitUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.sit_username
     *
     * @param sitUsername the value for system_info.sit_username
     *
     * @mbg.generated
     */
    public void setSitUsername(String sitUsername) {
        this.sitUsername = sitUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.sit_password
     *
     * @return the value of system_info.sit_password
     *
     * @mbg.generated
     */
    public String getSitPassword() {
        return sitPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.sit_password
     *
     * @param sitPassword the value for system_info.sit_password
     *
     * @mbg.generated
     */
    public void setSitPassword(String sitPassword) {
        this.sitPassword = sitPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.uat_address
     *
     * @return the value of system_info.uat_address
     *
     * @mbg.generated
     */
    public String getUatAddress() {
        return uatAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.uat_address
     *
     * @param uatAddress the value for system_info.uat_address
     *
     * @mbg.generated
     */
    public void setUatAddress(String uatAddress) {
        this.uatAddress = uatAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.uat_username
     *
     * @return the value of system_info.uat_username
     *
     * @mbg.generated
     */
    public String getUatUsername() {
        return uatUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.uat_username
     *
     * @param uatUsername the value for system_info.uat_username
     *
     * @mbg.generated
     */
    public void setUatUsername(String uatUsername) {
        this.uatUsername = uatUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.uat_password
     *
     * @return the value of system_info.uat_password
     *
     * @mbg.generated
     */
    public String getUatPassword() {
        return uatPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.uat_password
     *
     * @param uatPassword the value for system_info.uat_password
     *
     * @mbg.generated
     */
    public void setUatPassword(String uatPassword) {
        this.uatPassword = uatPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.dev_address
     *
     * @return the value of system_info.dev_address
     *
     * @mbg.generated
     */
    public String getDevAddress() {
        return devAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.dev_address
     *
     * @param devAddress the value for system_info.dev_address
     *
     * @mbg.generated
     */
    public void setDevAddress(String devAddress) {
        this.devAddress = devAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.dev_username
     *
     * @return the value of system_info.dev_username
     *
     * @mbg.generated
     */
    public String getDevUsername() {
        return devUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.dev_username
     *
     * @param devUsername the value for system_info.dev_username
     *
     * @mbg.generated
     */
    public void setDevUsername(String devUsername) {
        this.devUsername = devUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.dev_password
     *
     * @return the value of system_info.dev_password
     *
     * @mbg.generated
     */
    public String getDevPassword() {
        return devPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.dev_password
     *
     * @param devPassword the value for system_info.dev_password
     *
     * @mbg.generated
     */
    public void setDevPassword(String devPassword) {
        this.devPassword = devPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.prod_address
     *
     * @return the value of system_info.prod_address
     *
     * @mbg.generated
     */
    public String getProdAddress() {
        return prodAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.prod_address
     *
     * @param prodAddress the value for system_info.prod_address
     *
     * @mbg.generated
     */
    public void setProdAddress(String prodAddress) {
        this.prodAddress = prodAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.prod_username
     *
     * @return the value of system_info.prod_username
     *
     * @mbg.generated
     */
    public String getProdUsername() {
        return prodUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.prod_username
     *
     * @param prodUsername the value for system_info.prod_username
     *
     * @mbg.generated
     */
    public void setProdUsername(String prodUsername) {
        this.prodUsername = prodUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.prod_password
     *
     * @return the value of system_info.prod_password
     *
     * @mbg.generated
     */
    public String getProdPassword() {
        return prodPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.prod_password
     *
     * @param prodPassword the value for system_info.prod_password
     *
     * @mbg.generated
     */
    public void setProdPassword(String prodPassword) {
        this.prodPassword = prodPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pm_name
     *
     * @return the value of system_info.pm_name
     *
     * @mbg.generated
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pm_name
     *
     * @param pmName the value for system_info.pm_name
     *
     * @mbg.generated
     */
    public void setPmName(String pmName) {
        this.pmName = pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pm_email
     *
     * @return the value of system_info.pm_email
     *
     * @mbg.generated
     */
    public String getPmEmail() {
        return pmEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pm_email
     *
     * @param pmEmail the value for system_info.pm_email
     *
     * @mbg.generated
     */
    public void setPmEmail(String pmEmail) {
        this.pmEmail = pmEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pm_phone
     *
     * @return the value of system_info.pm_phone
     *
     * @mbg.generated
     */
    public String getPmPhone() {
        return pmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pm_phone
     *
     * @param pmPhone the value for system_info.pm_phone
     *
     * @mbg.generated
     */
    public void setPmPhone(String pmPhone) {
        this.pmPhone = pmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pm_manager
     *
     * @return the value of system_info.pm_manager
     *
     * @mbg.generated
     */
    public String getPmManager() {
        return pmManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pm_manager
     *
     * @param pmManager the value for system_info.pm_manager
     *
     * @mbg.generated
     */
    public void setPmManager(String pmManager) {
        this.pmManager = pmManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pm_manager_email
     *
     * @return the value of system_info.pm_manager_email
     *
     * @mbg.generated
     */
    public String getPmManagerEmail() {
        return pmManagerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pm_manager_email
     *
     * @param pmManagerEmail the value for system_info.pm_manager_email
     *
     * @mbg.generated
     */
    public void setPmManagerEmail(String pmManagerEmail) {
        this.pmManagerEmail = pmManagerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.dev_manager
     *
     * @return the value of system_info.dev_manager
     *
     * @mbg.generated
     */
    public String getDevManager() {
        return devManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.dev_manager
     *
     * @param devManager the value for system_info.dev_manager
     *
     * @mbg.generated
     */
    public void setDevManager(String devManager) {
        this.devManager = devManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.dev_manager_email
     *
     * @return the value of system_info.dev_manager_email
     *
     * @mbg.generated
     */
    public String getDevManagerEmail() {
        return devManagerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.dev_manager_email
     *
     * @param devManagerEmail the value for system_info.dev_manager_email
     *
     * @mbg.generated
     */
    public void setDevManagerEmail(String devManagerEmail) {
        this.devManagerEmail = devManagerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pmo
     *
     * @return the value of system_info.pmo
     *
     * @mbg.generated
     */
    public String getPmo() {
        return pmo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pmo
     *
     * @param pmo the value for system_info.pmo
     *
     * @mbg.generated
     */
    public void setPmo(String pmo) {
        this.pmo = pmo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.pmo_email
     *
     * @return the value of system_info.pmo_email
     *
     * @mbg.generated
     */
    public String getPmoEmail() {
        return pmoEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.pmo_email
     *
     * @param pmoEmail the value for system_info.pmo_email
     *
     * @mbg.generated
     */
    public void setPmoEmail(String pmoEmail) {
        this.pmoEmail = pmoEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.vendor_name
     *
     * @return the value of system_info.vendor_name
     *
     * @mbg.generated
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.vendor_name
     *
     * @param vendorName the value for system_info.vendor_name
     *
     * @mbg.generated
     */
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.vendor_email1
     *
     * @return the value of system_info.vendor_email1
     *
     * @mbg.generated
     */
    public String getVendorEmail1() {
        return vendorEmail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.vendor_email1
     *
     * @param vendorEmail1 the value for system_info.vendor_email1
     *
     * @mbg.generated
     */
    public void setVendorEmail1(String vendorEmail1) {
        this.vendorEmail1 = vendorEmail1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.vendor_email2
     *
     * @return the value of system_info.vendor_email2
     *
     * @mbg.generated
     */
    public String getVendorEmail2() {
        return vendorEmail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.vendor_email2
     *
     * @param vendorEmail2 the value for system_info.vendor_email2
     *
     * @mbg.generated
     */
    public void setVendorEmail2(String vendorEmail2) {
        this.vendorEmail2 = vendorEmail2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.vendor_email3
     *
     * @return the value of system_info.vendor_email3
     *
     * @mbg.generated
     */
    public String getVendorEmail3() {
        return vendorEmail3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.vendor_email3
     *
     * @param vendorEmail3 the value for system_info.vendor_email3
     *
     * @mbg.generated
     */
    public void setVendorEmail3(String vendorEmail3) {
        this.vendorEmail3 = vendorEmail3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.status
     *
     * @return the value of system_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.status
     *
     * @param status the value for system_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_info.create_time
     *
     * @return the value of system_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_info.create_time
     *
     * @param createTime the value for system_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}