package com.trident.security.dao;

import com.trident.security.bean.InVul;
import com.trident.security.bean.InVulExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InVulMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    long countByExample(InVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int deleteByExample(InVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int insert(InVul row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int insertSelective(InVul row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    List<InVul> selectByExample(InVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    InVul selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") InVul row, @Param("example") InVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") InVul row, @Param("example") InVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InVul row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_vul
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InVul row);
}