package com.trident.security.dao;

import com.trident.security.bean.OutVul;
import com.trident.security.bean.OutVulExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutVulMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    long countByExample(OutVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int deleteByExample(OutVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int insert(OutVul row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int insertSelective(OutVul row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    List<OutVul> selectByExample(OutVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    OutVul selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") OutVul row, @Param("example") OutVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") OutVul row, @Param("example") OutVulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OutVul row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_vul
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OutVul row);
}