package com.trident.security.dao;

import com.trident.security.bean.VulType;
import com.trident.security.bean.VulTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VulTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    long countByExample(VulTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int deleteByExample(VulTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int insert(VulType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int insertSelective(VulType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    List<VulType> selectByExample(VulTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    VulType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") VulType row, @Param("example") VulTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") VulType row, @Param("example") VulTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VulType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vul_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VulType row);
}